exclude: (^.idea/|^notebooks/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
        types: [ python ]
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        types: [python]
        require_serial: true
        entry: black
      - id: mypy
        name: mypy
        language: system
        types: [ python ]
        entry: mypy
        require_serial: true
        args: [ --strict, --python-version=3.6, --show-error-codes, --allow-untyped-decorators ]
  - repo: https://github.com/dustinsand/pre-commit-jvm
    rev: v0.4.0
    hooks:
      - id: google-java-formatter-jdk11
        args: [ --replace, --set-exit-if-changed ]
      - id: pmd
        args: [ -rulesets, pmd-ruleset.xml, -language, java, -cache, .pmd/cache, -dir, src/main/java, -dir, src/test/java, -f, textcolor ]
