version: '3.5'
services:
  fhir:
    depends_on:
      - mongo
    image: imranq2/node-fhir-server-mongo:2.1.76
    container_name: 'bsights_engine_spark_fhir'
    environment:
      SERVER_PORT: 3000
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      RESOURCE_SERVER: http://localhost:3000/
      AUTH_SERVER_URI: http://myauthzserver.com
      CLIENT_ID: client
      CLIENT_SECRET: secret
      INTROSPECTION_URL: https://myauthzserver.com/introspect
      MONGO_DB_NAME: fhir
      CHECK_ACCESS_TAG_ON_SAVE: 1
      IS_PRODUCTION:
      RETURN_BUNDLE: "1"
      VALIDATE_SCHEMA: "1"
      AUTH_ENABLED: "0"
      ENABLE_GRAPHQL: "1"
      LOGLEVEL: "DEBUG"
      SET_INDEX_HINTS: 0
      CREATE_INDEX_ON_COLLECTION_CREATION: 1
      USE_TWO_STEP_SEARCH_OPTIMIZATION: "1"
    ports:
      - '3000:3000'
    command: yarn start
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:3000/health || exit 1"]

  mongo:
    image: docker.io/bitnami/mongodb:4.4.12
    container_name: 'bsights_engine_spark_mongodb'
    ports:
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo_data:/bitnami/mongodb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet

  scriptrunner:
    image: python:3.8.12-slim-buster
    container_name: 'bsights-engine-spark-scriptrunner'
    volumes:
      - ./scripts/load_fhir_server.py:/scripts/load_fhir_server.py
      - ./src/test/resources/awvcn/cql:/data/cql/awvcn/
      - ./src/test/resources/awvcn/terminology:/data/terminology/awvcn/
      - ./src/test/resources/bmi/cql:/data/cql/bmi/
      - ./src/test/resources/bmi/terminology:/data/terminology/bmi/
      - ./src/test/resources/diab/cql:/data/cql/diab/
      - ./src/test/resources/diab/terminology:/data/terminology/diab/
    command: tail -f /dev/null

volumes:
  mongo_data:
