version: '3.5'
services:
  dev:
    depends_on:
      - fhir
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/helix.pipelines/
    container_name: helix.bSights.cql_spark_engine
    environment:
      LOGLEVEL: DEBUG

  fhir:
    depends_on:
      - mongo
    image: imranq2/node-fhir-server-mongo:2.0.80
    # To use local fhir code, comment above line and uncomment below
    #    build:
    #      dockerfile: Dockerfile
    #      context: ../node-fhir-server-mongo
    environment:
      SERVER_PORT: 3000
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      RESOURCE_SERVER: http://fhir:3000/
      AUTH_SERVER_URI: http://myauthzserver.com
      CLIENT_ID: client
      CLIENT_SECRET: secret
      INTROSPECTION_URL: https://myauthzserver.com/introspect
      MONGO_DB_NAME: fhir
      CHECK_ACCESS_TAG_ON_SAVE: 1
      IS_PRODUCTION:
      RETURN_BUNDLE: "1"
      VALIDATE_SCHEMA: "1"
      AUTH_ENABLED: "0"
      ENABLE_GRAPHQL: "1"
    ports:
      - '3000:3000'
    command: yarn start
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:3000/health || exit 1"]

  mongo:
    image: docker.io/bitnami/mongodb:4.4.9
    ports:
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo_data:/bitnami/mongodb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet

version: '3.5'
services:
  dev:
    depends_on:
      - fhir
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/helix.pipelines/
    container_name: helix.bSights.cql_spark_engine
    environment:
      LOGLEVEL: DEBUG

  fhir:
    depends_on:
      - mongo
    image: imranq2/node-fhir-server-mongo:2.0.80
    # To use local fhir code, comment above line and uncomment below
    #    build:
    #      dockerfile: Dockerfile
    #      context: ../node-fhir-server-mongo
    environment:
      SERVER_PORT: 3000
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      RESOURCE_SERVER: http://fhir:3000/
      AUTH_SERVER_URI: http://myauthzserver.com
      CLIENT_ID: client
      CLIENT_SECRET: secret
      INTROSPECTION_URL: https://myauthzserver.com/introspect
      MONGO_DB_NAME: fhir
      CHECK_ACCESS_TAG_ON_SAVE: 1
      IS_PRODUCTION:
      RETURN_BUNDLE: "1"
      VALIDATE_SCHEMA: "1"
      AUTH_ENABLED: "0"
      ENABLE_GRAPHQL: "1"
    ports:
      - '3000:3000'
    command: yarn start
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:3000/health || exit 1"]

  mongo:
    image: docker.io/bitnami/mongodb:4.4.9
    ports:
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo_data:/bitnami/mongodb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet

  scriptrunner:
    image: python:3.8.12-slim-buster
    volumes:
      - ./scripts:/scripts/
    command: tail -f /dev/null

volumes:
  mongo_data:
